# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66c8418e8212945f50e9b43b07528387008ae69d2713e4d76d84646196700682285c06cf32356c050890f2ae4884578d7a9e1d6204f11feb9702d092a0193531

test:
  secret_key_base: ebc6fc9115356f31b90426e3d39575f3ac7bbf34d40098d626386857f50e62cc003b8bd12bdda999bee8574a7db571f8d979edc71261a244365e28146460e283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
